### ISSUE TITLE
Other options that Record all desktop doesn't work on Ubuntu 18.10 Gnome Wayland

### ISSUE THREAD

**Issue by singleman68** [EasyScreenCast/EasyScreenCast#211]
Other options that Record all desktop doesn't work on Ubuntu 18.10 Gnome Wayland
## Expected Behavior
Should be appear a pointer to select an area or window after to start record
## Current Behavior
The screen except upper bar is frozen. I need to restart session to access work area.

## Logs
JS WARNING: [/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js 268]: Too many arguments to method Clutter.Actor.add_child: expected 1, got 2
JS WARNING: [/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js 511]: Too many arguments to method Clutter.Actor.add_child: expected 1, got 2
JS WARNING: [/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js 833]: reference to undefined property "MESSAGE_TRAY"
JS WARNING: [/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js 230]: reference to undefined property "CtrlWebcam"
0 _syncCmd() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilexecmd.js":148]
1 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
2 Execute() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilexecmd.js":84]
3 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
4 _initTabFile() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":667]
5 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
6 _init() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":96]
7 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
8 buildPrefsWidget() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":1060]
9 _selectExtension() ["resource:///org/gnome/shell/extensionPrefs/main.js":83]
10 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
11 _onCommandLine() ["resource:///org/gnome/shell/extensionPrefs/main.js":235]
12 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
14 main() ["resource:///org/gnome/shell/extensionPrefs/main.js":389]
0 _syncCmd() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilexecmd.js":149]
1 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
2 Execute() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilexecmd.js":84]
3 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
4 _initTabFile() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":667]
5 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
6 _init() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":96]
7 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
8 buildPrefsWidget() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":1060]
9 _selectExtension() ["resource:///org/gnome/shell/extensionPrefs/main.js":83]
10 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
11 _onCommandLine() ["resource:///org/gnome/shell/extensionPrefs/main.js":235]
12 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
14 main() ["resource:///org/gnome/shell/extensionPrefs/main.js":389]
0 _syncCmd() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilexecmd.js":153]
1 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
2 Execute() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilexecmd.js":84]
3 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
4 _initTabFile() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":667]
5 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
6 _init() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":96]
7 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
8 buildPrefsWidget() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":1060]
9 _selectExtension() ["resource:///org/gnome/shell/extensionPrefs/main.js":83]
10 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
11 _onCommandLine() ["resource:///org/gnome/shell/extensionPrefs/main.js":235]
12 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
14 main() ["resource:///org/gnome/shell/extensionPrefs/main.js":389]
0 _syncCmd() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilexecmd.js":148]
1 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
2 Execute() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilexecmd.js":84]
3 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
4 _initTabFile() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":667]
5 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
6 _init() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":96]
7 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
8 buildPrefsWidget() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":1060]
9 _selectExtension() ["resource:///org/gnome/shell/extensionPrefs/main.js":83]
10 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
11 _onCommandLine() ["resource:///org/gnome/shell/extensionPrefs/main.js":235]
12 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
14 main() ["resource:///org/gnome/shell/extensionPrefs/main.js":389]
0 _syncCmd() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilexecmd.js":149]
1 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
2 Execute() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilexecmd.js":84]
3 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
4 _initTabFile() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":667]
5 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
6 _init() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":96]
7 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
8 buildPrefsWidget() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":1060]
9 _selectExtension() ["resource:///org/gnome/shell/extensionPrefs/main.js":83]
10 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
11 _onCommandLine() ["resource:///org/gnome/shell/extensionPrefs/main.js":235]
12 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
14 main() ["resource:///org/gnome/shell/extensionPrefs/main.js":389]
0 _syncCmd() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilexecmd.js":153]
1 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
2 Execute() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilexecmd.js":84]
3 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
4 _initTabFile() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":667]
5 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
6 _init() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":96]
7 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
8 buildPrefsWidget() ["/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js":1060]
9 _selectExtension() ["resource:///org/gnome/shell/extensionPrefs/main.js":83]
10 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
11 _onCommandLine() ["resource:///org/gnome/shell/extensionPrefs/main.js":235]
12 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
14 main() ["resource:///org/gnome/shell/extensionPrefs/main.js":389]
JS WARNING: [/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js 115]: reference to undefined property "screen"
_setCaptureCursor@/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js:115:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_init@/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js:89:13
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
_init@/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js:213:25
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
_doRecording@/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:631:25
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_addMIRecording/<@/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:279:17
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
activate@resource:///org/gnome/shell/ui/popupMenu.js:175:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_onButtonReleaseEvent@resource:///org/gnome/shell/ui/popupMenu.js:127:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_setCaptureCursor@/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js:115:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_init@/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js:89:13
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
_init@/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js:213:25
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
_doRecording@/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:631:25
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_addMIRecording/<@/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:279:17
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
activate@resource:///org/gnome/shell/ui/popupMenu.js:175:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_onButtonReleaseEvent@resource:///org/gnome/shell/ui/popupMenu.js:127:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
JS WARNING: [resource:///org/gnome/shell/ui/windowManager.js 1564]: reference to undefined property "MetaWindowXwayland"
JS WARNING: [/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js 268]: Too many arguments to method Clutter.Actor.add_child: expected 1, got 2
JS WARNING: [/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js 511]: Too many arguments to method Clutter.Actor.add_child: expected 1, got 2
JS WARNING: [/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js 833]: reference to undefined property "MESSAGE_TRAY"
0 loadInterfaceXml() ["/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/interfaces.js":38]
1 <TOP LEVEL> ["/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/interfaces.js":17]
2 <TOP LEVEL> ["/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js":28]
3 <TOP LEVEL> ["/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js":30]
4 <TOP LEVEL> ["/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/statusNotifierWatcher.js":28]
5 <TOP LEVEL> ["/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/extension.js":21]
6 initExtension() ["resource:///org/gnome/shell/ui/extensionSystem.js":241]
7 loadExtension() ["resource:///org/gnome/shell/ui/extensionSystem.js":178]
8 _loadExtensions/<() ["resource:///org/gnome/shell/ui/extensionSystem.js":328]
9 _emit() ["resource:///org/gnome/gjs/modules/signals.js":128]
10 _loadExtension() ["resource:///org/gnome/shell/misc/extensionUtils.js":193]
11 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
12 scanExtensions/<() ["resource:///org/gnome/shell/misc/extensionUtils.js":199]
13 collectFromDatadirs() ["resource:///org/gnome/shell/misc/fileUtils.js":28]
14 scanExtensions() ["resource:///org/gnome/shell/misc/extensionUtils.js":198]
15 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
16 _loadExtensions() ["resource:///org/gnome/shell/ui/extensionSystem.js":330]
17 enableAllExtensions() ["resource:///org/gnome/shell/ui/extensionSystem.js":338]
18 _sessionUpdated() ["resource:///org/gnome/shell/ui/extensionSystem.js":369]
19 init() ["resource:///org/gnome/shell/ui/extensionSystem.js":377]
20 _initializeUI() ["resource:///org/gnome/shell/ui/main.js":232]
21 start() ["resource:///org/gnome/shell/ui/main.js":136]
JS WARNING: [/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/appIcons.js 1052]: unreachable code after return statement
JS WARNING: [/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js 230]: reference to undefined property "CtrlWebcam"
JS WARNING: [/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js 115]: reference to undefined property "screen"
_setCaptureCursor@/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js:115:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_init@/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js:89:13
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
_init@/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/selection.js:261:25
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
_doRecording@/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:634:25
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_addMIRecording/<@/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:279:17
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
activate@resource:///org/gnome/shell/ui/popupMenu.js:175:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_onButtonReleaseEvent@resource:///org/gnome/shell/ui/popupMenu.js:127:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
JS WARNING: [resource:///org/gnome/shell/ui/windowManager.js 1564]: reference to undefined property "MetaWindowXwayland"
JS WARNING: [/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js 268]: Too many arguments to method Clutter.Actor.add_child: expected 1, got 2
JS WARNING: [/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js 511]: Too many arguments to method Clutter.Actor.add_child: expected 1, got 2
JS WARNING: [/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js 833]: reference to undefined property "MESSAGE_TRAY"
0 loadInterfaceXml() ["/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/interfaces.js":38]
1 <TOP LEVEL> ["/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/interfaces.js":17]
2 <TOP LEVEL> ["/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js":28]
3 <TOP LEVEL> ["/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js":30]
4 <TOP LEVEL> ["/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/statusNotifierWatcher.js":28]
5 <TOP LEVEL> ["/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/extension.js":21]
6 initExtension() ["resource:///org/gnome/shell/ui/extensionSystem.js":241]
7 loadExtension() ["resource:///org/gnome/shell/ui/extensionSystem.js":178]
8 _loadExtensions/<() ["resource:///org/gnome/shell/ui/extensionSystem.js":328]
9 _emit() ["resource:///org/gnome/gjs/modules/signals.js":128]
10 _loadExtension() ["resource:///org/gnome/shell/misc/extensionUtils.js":193]
11 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
12 scanExtensions/<() ["resource:///org/gnome/shell/misc/extensionUtils.js":199]
13 collectFromDatadirs() ["resource:///org/gnome/shell/misc/fileUtils.js":28]
14 scanExtensions() ["resource:///org/gnome/shell/misc/extensionUtils.js":198]
15 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
16 _loadExtensions() ["resource:///org/gnome/shell/ui/extensionSystem.js":330]
17 enableAllExtensions() ["resource:///org/gnome/shell/ui/extensionSystem.js":338]
18 _sessionUpdated() ["resource:///org/gnome/shell/ui/extensionSystem.js":369]
19 init() ["resource:///org/gnome/shell/ui/extensionSystem.js":377]
20 _initializeUI() ["resource:///org/gnome/shell/ui/main.js":232]
21 start() ["resource:///org/gnome/shell/ui/main.js":136]
JS WARNING: [/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/appIcons.js 1052]: unreachable code after return statement
JS WARNING: [resource:///org/gnome/shell/ui/search.js 506]: reference to undefined property "_searchCancelTimeoutId"
JS WARNING: [resource:///org/gnome/shell/ui/search.js 599]: reference to undefined property "_searchCancelTimeoutId"
JS WARNING: [/home/user_name/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js 230]: reference to undefined property "CtrlWebcam"

My Environment
I used gnome extension website on Gnome Shell 3.30.1 on Ubuntu 18.10 Wayland

**Comment by letorbi** [comment]
I have the same problems on X.org / Arch Linux.

I can record a screencast of the whole desktop, but not of a window or a selected area.

**Comment by ab0v3g4me** [comment]
I can confirm that this is happening as well on my side.

**Comment by letorbi** [comment]
@ab0v3g4me Can you tell your system configuration? Is it one of the above or a new one?

**Comment by ab0v3g4me** [comment]
The same as you described it. Recording the desktop works, but other options freeze everything except the menu bar.
```
$ uname -a 
Linux Abovegame 4.14.82-1-lts #1 SMP Wed Nov 21 14:23:34 CET 2018 x86_64 GNU/Linux
```
As for gnome it's version 3.30.2.

**Comment by letorbi** [comment]
Actually the bug descibed here seems to be a duplicate of #210

**Comment by tobias47n9e** [comment]
I added a fix for screen and window recording. Obviously some testing of the master branch would be nice.

**Comment by tobias47n9e** [comment]
@singleman68 Maybe because I was missing a JS file in the Makefile. Can you try again? Bonus points for testing with Wayland and X :smile:

**Comment by letorbi** [comment]
I can confirm that everything works in X11 now. Unfortunately I cannot test Wayland :(

**Comment by singleman68** [comment]
With Wayland works correctly if I deactivate show border selected area option.

**Comment by klaaslusterbroodvan** [comment]
In Fedora 32, it works fine with Gnome/X11, but **not** with Gnome/Wayland. 

If you install the latest EasyScreenCast plugin and login to the Gnome/Wayland session it will simply hang your whole system requiring a reboot. It works perfectly fine in Gnome/X11. Does anyone have tips on how to debug this (it is hard to check what is going on when the system hangs).

I look forward to get this to work, given that it seems to be the only user-friendly screencast recording software under wayland. Any tips and help are appreciated.

**Comment by matty0blake** [comment]
my easy screen cast dont work and dont show options when i click on it it but when i open options fron chrome it say something gone wrong 
say this:


The settings of extension EasyScreenCast@iacopodeenosee.gmail.com had an error:
```
ReferenceError: global is not defined
```

Stack trace:
```
TalkativeLog@/home/julian/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/convenience.js:116:9
buildPrefsWidget@/home/julian/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:1188:9
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

help please i need it cause other screen recorders dont work i use kali linux 2020.1 gnome

**Comment by y-alt** [comment]
I had the same error after switching from **Record selected area**  to **Record all desktop**.

Selecting back Record selected area option, and resizing the area to record seems to fix the issue. but I can't reproduce the error

```
❯ name -a
Linux UB2004-Lenovo-G50-45 5.4.0-39-generic #43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

**Comment by y-alt** [comment]
add technical details, and remove unverifiable info

**Comment by y-alt** [comment]
it is not the same issue

**Comment by sreeram-boyapati** [comment]
I am facing the same issue
