### ISSUE TITLE
I cannot get EasyScreenCast to work on my Fedora 31 Kernel 5.4.12-200.fc31.x86_64 .  I really like this app but I cannot seem to get it working

### ISSUE THREAD

**Issue by robertdaleweir** [EasyScreenCast/EasyScreenCast#240]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Logs

 * Use `journalctl /usr/bin/gnome-shell -f` to monitor Gnome shell activity. Maybe the crash will log something.
 * Log, **enable verbose debug logs** into options window, and after that try  
 `journalctl --since=today --no-pager | grep js`
 * webcam info:
 `v4l2-ctl --all`
 * webcam info:
 `for VIDEO_DEVICE in /dev/video* ; do echo ; echo ; echo $VIDEO_DEVICE ; echo ; v4l2-ctl --device=$VIDEO_DEVICE --list-inputs ; done`
 * webcam info:
 `GST_DEBUG=v4l2src:5 gst-launch-1.0 v4l2src num-buffers=1 ! fakesink | grep probed`

## Your Environment

* Where did you download the extension?
 [ ] Gnome shell extension website
 [ ] From Git (Add commit tag)
* Gnome shell version:

* Operating System and version:

* Display server: Wayland / X11 / Other

**Comment by robertdaleweir** [comment]
[root@LENOVO ~]# journalctl /usr/bin/gnome-shell -f
-- Logs begin at Wed 2020-01-15 13:42:04 PST. --
Jan 25 21:51:24 LENOVO gnome-shell[3173]: JS WARNING: [/home/me/.local/share/gnome-shell/extensions/imap_notify@kirby33/extension.js 79]: Too many arguments to function GLib.spawn_sync: expected 5, got 9
Jan 25 21:51:24 LENOVO gnome-shell[3173]:   File "/home/me/.local/share/gnome-shell/extensions/imap_notify@kirby33/checkmail.py", line 48
Jan 25 21:51:24 LENOVO gnome-shell[3173]:     print "count is "+str(xnbmail)
Jan 25 21:51:24 LENOVO gnome-shell[3173]:                     ^
Jan 25 21:51:24 LENOVO gnome-shell[3173]: SyntaxError: invalid syntax
Jan 25 21:51:34 LENOVO gnome-shell[3173]: JS WARNING: [/home/me/.local/share/gnome-shell/extensions/imap_notify@kirby33/extension.js 79]: Too many arguments to function GLib
[root@LENOVO ~]# v4l2-ctl --all
Driver Info:
	Driver name      : uvcvideo
	Card type        : Integrated Camera: Integrated C
	Bus info         : usb-0000:03:00.3-1
	Driver version   : 5.4.12
	Capabilities     : 0x84a00001
		Video Capture
		Metadata Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x04200001
		Video Capture
		Streaming
		Extended Pix Format
Media Driver Info:
	Driver name      : uvcvideo
	Model            : Integrated Camera: Integrated C
	Serial           : 0001
	Bus info         : usb-0000:03:00.3-1
	Media version    : 5.4.12
	Hardware revision: 0x00000027 (39)
	Driver version   : 5.4.12
Interface Info:
	ID               : 0x03000002
	Type             : V4L Video
Entity Info:
	ID               : 0x00000001 (1)
	Name             : Integrated Camera: Integrated C
	Function         : V4L2 I/O
	Flags         : default
	Pad 0x01000007   : 0: Sink
	  Link 0x02000013: from remote pad 0x100000a of entity 'Realtek Extended Controls Unit': Data, Enabled, Immutable
Priority: 2
Video input : 0 (Camera 1: ok)
Format Video Capture:
	Width/Height      : 1280/720
	Pixel Format      : 'MJPG' (Motion-JPEG)
	Field             : None
	Bytes per Line    : 0
	Size Image        : 1843200
	Colorspace        : sRGB
	Transfer Function : Default (maps to sRGB)
	YCbCr/HSV Encoding: Default (maps to ITU-R 601)
	Quantization      : Default (maps to Full Range)
	Flags             : 
Crop Capability Video Capture:
	Bounds      : Left 0, Top 0, Width 1280, Height 720
	Default     : Left 0, Top 0, Width 1280, Height 720
	Pixel Aspect: 1/1
Selection Video Capture: crop_default, Left 0, Top 0, Width 1280, Height 720, Flags: 
Selection Video Capture: crop_bounds, Left 0, Top 0, Width 1280, Height 720, Flags: 
Streaming Parameters Video Capture:
	Capabilities     : timeperframe
	Frames per second: 30.000 (30/1)
	Read buffers     : 0
                     brightness 0x00980900 (int)    : min=0 max=255 step=1 default=128 value=128
                       contrast 0x00980901 (int)    : min=0 max=255 step=1 default=32 value=32
                     saturation 0x00980902 (int)    : min=0 max=100 step=1 default=64 value=64
                            hue 0x00980903 (int)    : min=-180 max=180 step=1 default=0 value=0
 white_balance_temperature_auto 0x0098090c (bool)   : default=1 value=1
                          gamma 0x00980910 (int)    : min=90 max=150 step=1 default=120 value=120
           power_line_frequency 0x00980918 (menu)   : min=0 max=2 default=1 value=1
				0: Disabled
				1: 50 Hz
				2: 60 Hz
      white_balance_temperature 0x0098091a (int)    : min=2800 max=6500 step=10 default=4600 value=4600 flags=inactive
                      sharpness 0x0098091b (int)    : min=0 max=7 step=1 default=0 value=0
         backlight_compensation 0x0098091c (int)    : min=0 max=2 step=1 default=1 value=1
                  exposure_auto 0x009a0901 (menu)   : min=0 max=3 default=3 value=3
				1: Manual Mode
				3: Aperture Priority Mode
              exposure_absolute 0x009a0902 (int)    : min=2 max=1250 step=1 default=156 value=156 flags=inactive
         exposure_auto_priority 0x009a0903 (bool)   : default=0 value=1
[root@LENOVO ~]# 

[root@LENOVO ~]# GST_DEBUG=v4l2src:5 gst-launch-1.0 v4l2src num-buffers=1 ! fakesink | grep probed

** (gst-plugin-scanner:14141): CRITICAL **: 21:57:31.827: Couldn't g_module_open libpython. Reason: /usr/lib64/libpython3.7m.so: cannot open shared object file: No such file or directory
...
[root@LENOVO ~]# for VIDEO_DEVICE in /dev/video* ; do echo ; echo ; echo $VIDEO_DEVICE ; echo ; v4l2-ctl --device=$VIDEO_DEVICE --list-inputs ; done


/dev/video0

ioctl: VIDIOC_ENUMINPUT
	Input       : 0
	Name        : Camera 1
	Type        : 0x00000002 (Camera)
	Audioset    : 0x00000000
	Tuner       : 0x00000000
	Standard    : 0x0000000000000000 ()
	Status      : 0x00000000 (ok)
	Capabilities: 0x00000000 (not defined)


/dev/video1

ioctl: VIDIOC_ENUMINPUT
[root@LENOVO ~]# webcam info:
Where did you download the extension?

Obtained  From Git (Add commit tag)  Not sure about commit tag.


[root@LENOVO ~]# dnf list installed | grep gnome-shell
chrome-gnome-shell.x86_64                          10.1-5.fc31                            @fedora                   
gnome-shell.x86_64                                 3.34.3-1.fc31                          @updates   

[root@LENOVO ~]# uname -a
Linux LENOVO 5.4.12-200.fc31.x86_64 #1 SMP Tue Jan 14 20:07:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@LENOVO ~]# 

Display Server X11

**Comment by santosventer** [comment]
Having a similar problem, I cant get it working on gnome 3.34.
Any help with this?

**Comment by somethingGoneWrong** [comment]
@santosventer @robertdaleweir  install the last git version:
```
git clone https://github.com/EasyScreenCast/EasyScreenCast.git
cd EasyScreenCast
make
make install
```
enable it and execute this[1] to see the log error and paste it here.
[1] ` journalctl --since=today --no-pager`

**Comment by robertdaleweir** [comment]
> @santosventer @robertdaleweir install the last git version:
> 
> ```
> git clone https://github.com/EasyScreenCast/EasyScreenCast.git
> cd EasyScreenCast
> make
> make install
> ```
> 
> enable it and execute this[1] to see the log error and paste it here.
> [1] ` journalctl --since=today --no-pager`

I have responded to your email.  I can say that as of invoking your instructions IT WORKS!  I am elated.
Thanks for all your efforts.  : - )))
Robert
PS  Keep up the GREAT work!

**Comment by santosventer** [comment]
@robertdaleweir its not allowing me to enable it, is there a different way to do it.
Check this out
![easy](https://user-images.githubusercontent.com/8567529/73638592-618c7600-4673-11ea-9aa6-537e508aacbc.png)

**Comment by bartoszek** [comment]
Try uninstalling from [gnome extensions.](https://extensions.gnome.org/extension/690/easyscreencast/) :thinking:
